server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/smart_qr_restaurant}
      database: smart_qr_restaurant

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:s.tsahilvarma04@gmail.com}
    password: ${MAIL_PASSWORD:Sahil@2005OK}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:SmartQRRestaurantSuperSecretKeyForJWTTokenGeneration2024VeryLongAndSecure}
    expiration-ms: 86400000
  frontend-url: ${FRONTEND_URL:https://your-frontend-url.com}

logging:
  level:
    root: WARN
    net.engineeringdigest.journalApp: INFO
